### ISSUE TITLE
Channel names do not save

### ISSUE THREAD

**Issue by smith6jt-cop** [schienstockd/cecelia-legacy#1]
Working through tutorial on Windows 10, docker install.  Successfully completed the first two steps, but trying "Cleanup images" the channel names are reverted to default.  Went back to the previous step and received a runtime error
[log.txt](https://github.com/user-attachments/files/18285834/log.txt)

**Comment by schienstockd** [comment]
Thanks for working through this! When you change the channel names you must click `Save` in the `Project` box.

![Screenshot 2025-01-02 at 13-44-40 Cecelia](https://github.com/user-attachments/assets/ae870c55-da57-4663-948e-163f56f3f85b)

I saw something else in the error log:

```python
app-1  |   Cell In[1], line 1
app-1  |     napari_utils.task_dir = 'C:\Users\smith\cecelia\PROJECTS/o9F8Nh/ANALYSIS/1/X3ZQiB'
app-1  |                                                                                       ^
app-1  | SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

Can you check the `datashare/docker.yml` file and make sure you have double backslash? It should look like this, otherwise the single backslash will cause the string to be interpreted as unicode character:

```yml
default:
  docker:
    useDocker: TRUE
    pathMapping:
      home:
        from: "/home/shiny/local/cecelia"
        to: "D:\\Public\\Cecelia\\GIT\\ceceliaDocker\\datashare\\cecelia"
      projects:
        from: "/cecelia/projects"
        to: "D:\\Public\\Cecelia\\PROJECTS"
```

Let me know.
